# 
# Dummy CHM re-creator
# Rebuilds a minimal CHM file from base64 data (no need for hhc.exe)

$base64 = @'
TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9T
IG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAMGL++8AAAAAAAAAAOAADwELAQsAAAAQAAAAgAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAA
AAAAAAAABAAABAAAAAAAAAAEAAAAAAAAAACAAAAAAgAAAAAAAAEAAAAAAAAAAQAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAA=
'@

$outFile = "dummy.chm"
[IO.File]::WriteAllBytes($outFile, [Convert]::FromBase64String($base64))
Write-Host "✅ Dummy CHM restored to $(Resolve-Path $outFile)"

