use Net::SSH::Perl;
use Data::Dumper;

my $hostname = '192.168.56.101';
my $username = 'bitnami';
my $password = 'bayview_123';
$hostname = '192.168.56.102';
$username = 'cyg_server';

my $shell_command = <<'END_COMMAND';
if [ -e '/cygdrive/c/Windows/system32/cmd.exe' ]
then
if [ -e '/cygdrive/c/Program Files/IIS/Microsoft Web Deploy V3/msdeploy.exe' ]
then

# Generate the CMD script to run msdeploy.exe

cat << END_CMD_SCRIPT  > /cygdrive/c/Users/Administrator/Desktop/healthcheck.$$.cmd

@echo OFF
REM generated by $USER 
REM connected via $SSH_CLIENT 
msdeploy.exe -verb:getSystemInfo -source:apphostconfig="Default Web Site"
REM Detect if run under cygwin and refrain calling choice.exe
if "%SHELL%" neq "" goto :EOF
choice.exe /d y /t 5 > NUL 
goto :EOF

END_CMD_SCRIPT

echo Invoking cmd.exe to call msdeploy.exe for health check on windows host

/cygdrive/c/Windows/system32/cmd.exe /c "c:\\Users\\Administrator\\Desktop\\healthcheck.$$.cmd"

# 
else
echo The msdeploy is not installed on this  windows host 

fi
else
echo This is not a windows host 
fi

END_COMMAND

my $ssh_command = '/bin/bash -s';
my $ssh = Net::SSH::Perl->new( $hostname, debug => 0 );
$ssh->login( $username, $password );

my ( $stdout, $stderr, $exitcode ) = $ssh->cmd( $ssh_command, $shell_command );
print STDERR Dumper \[ $stdout, $stderr, $exitcode ];

1;

__END__

