spring:
  application:
    name: spring-mongo-crud
  datasource:
    database1:
      url: 'jdbc:postgresql://localhost:5432/DB_NAME'
      username: user
      password: ENC(AAtJwmQioe5oOai++Nu7r7ucxyZNXVPP2AEmA22NOhkSveAtvNaLCSdJ2tLfhLV2)
      driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: true
        open-in-view: false
        generate-ddl: true
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        properties:
          hibernate:
            format_sql: true
            order_inserts: true
            order_updates: true
            jdbc:
              batch_size: 15
            globally_quoted_identifiers: true
            globally_quoted_identifiers_skip_column_definitions: true
            query:
              plan_cache_max_size: 4096
              #fail_on_pagination_over_collection_fetch: true
              in_clause_parameter_padding: true
        hibernate:
          ddl-auto: update
    database2:
      data:
        mongodb:
          uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${spring.application.name}"
  profiles:
    active: local
