---
ad8c3125:
  datacenter: wec
  consul_node_name: service-discovery-server-0
  branch_name: cert
  environment: prod
  unused1:
  unused2:
  unused3:
  unused4:
e530095c:
  datacenter: wec
  consul_node_name: service-discovery-server-1
  branch_name: cert
  environment: prod
  unused1:
  unused2:
  unused3:
  unused4:
'0fd44821':
  datacenter: wec
  consul_node_name: service-discovery-server-2
  branch_name: cert_bcp
  # another name for cert 
  environment: prod
  unused1:
  unused2:
  unused3:
  unused4:
e577775c:
  datacenter: oxdc
  consul_node_name: apim-ap-manager-publisher-0
  branch_name: sandbox
# new environment - need to allow
  environment: test
  unused1:
  unused2:
  unused3:
  unused4:
f32b0fb0:
  datacenter: wec
  consul_node_name: service-discovery-server-2
  branch_name: cert
  environment: prod
  unused1:
  unused2:
  unused3:
  unused4:
node_to_ignore:
  datacenter: wec
  branch_name: cert
  environment: prod
  server_role: 'internal'
  unused1:
  unused2:
  unused3:
  unused4:
'3232bdc1':
  datacenter: oxdc
  consul_node_name: apim-ap-manager-publisher-0
  branch_name: new_env
# new environment - need to allow
  environment: test
  unused1:
  unused2:
  unused3:
  unused4:
